(()=>{"use strict";
const cfg=OKINAMAP_CONFIG,spots=OKINAMAP_SPOTS||[],filterSpec=OKINAMAP_FILTERS,$=id=>document.getElementById(id);let map,markers=[],activeFilters={categories:[],tags:{}},draftFilters=structuredClone(activeFilters),currentGroup=[],currentGroupIndex=0,userMarker=null,lastPosition=null,toastTimer;
const categoryIcons={"飲食店":'<path d="M7 3v7M4 3v4c0 2 6 2 6 0V3M7 10v11M15 3v18M15 3c5 2 5 9 0 10"/>',"カフェ":'<path d="M5 8h11v7a5 5 0 0 1-5 5h-1a5 5 0 0 1-5-5zM16 10h2a3 3 0 0 1 0 6h-2M8 3c-2 2 2 2 0 4M13 3c-2 2 2 2 0 4"/>',"ビーチ":'<path d="M3 15c3-4 6 4 9 0s6 4 9 0M3 20c3-4 6 4 9 0s6 4 9 0M6 11c2-5 10-7 14-3-3 0-4 1-5 3-2-2-4-2-5 0-1-2-2-3-4-3"/>',"その他":'<path d="m12 3 2.4 5 5.6.8-4 4 .9 5.7-4.9-2.7-4.9 2.7.9-5.7-4-4 5.6-.8z"/>'};
const validKey=()=>cfg.mapTilerKey&&cfg.mapTilerKey!=="YOUR_MAPTILER_API_KEY",markerSvg=c=>`<svg viewBox="0 0 24 24" aria-hidden="true">${categoryIcons[c]||categoryIcons["その他"]}</svg>`;
function groupedSpots(list=spots){const g=new Map;list.forEach(s=>{const k=s.groupId||`single:${s.id}`;if(!g.has(k))g.set(k,[]);g.get(k).push(s)});return[...g.values()]}
function filteredSpots(f){return spots.filter(s=>{const c=!f.categories.length||f.categories.includes(s.category),gs=Object.values(f.tags).filter(a=>a.length);return c&&gs.every(tags=>tags.some(t=>s.tags.includes(t)))})}
function initMap(){if(!validKey()){$("setupMessage").hidden=false;return}map=new maplibregl.Map({container:"map",style:cfg.mapStyle.replace("{KEY}",encodeURIComponent(cfg.mapTilerKey)),center:cfg.initialCenter,zoom:cfg.initialZoom,minZoom:cfg.minZoom,maxZoom:cfg.maxZoom,maxBounds:cfg.maxBounds,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:false}),"bottom-right");map.addControl(new maplibregl.AttributionControl({compact:true}),"bottom-right");map.on("load",renderMarkers)}
function renderMarkers(){markers.forEach(x=>x.marker.remove());markers=[];groupedSpots(filteredSpots(activeFilters)).forEach(group=>{const p=group[0],anchor=document.createElement("div");anchor.className="marker-anchor";const button=document.createElement("button");button.type="button";button.className="custom-marker";button.innerHTML=markerSvg(p.category);button.ariaLabel=group.length>1?`${group.length}件のスポット`:p.name;button.onclick=e=>{e.stopPropagation();openGroup(group)};anchor.appendChild(button);if(group.length>1){const badge=document.createElement("span");badge.className="count-badge";badge.textContent=group.length;anchor.appendChild(badge)}const marker=new maplibregl.Marker({element:anchor,anchor:"center",offset:[0,0]}).setLngLat(p.coordinates).addTo(map);markers.push({marker,button,ids:group.map(s=>s.id)})})}
function openGroup(group){currentGroup=group;currentGroupIndex=0;markers.forEach(m=>m.button.classList.toggle("is-selected",m.ids.some(id=>group.some(s=>s.id===id))));showSpot();$("spotSheet").classList.add("is-open");$("spotSheet").setAttribute("aria-hidden","false");map.easeTo({center:group[0].coordinates,offset:[0,-Math.min($("spotSheet").scrollHeight||360,innerHeight*.52)*.42],duration:420})}
function showSpot(){const s=currentGroup[currentGroupIndex];$("spotName").textContent=s.name;$("spotCategory").textContent=s.category;$("spotDescription").textContent=s.description;$("spotNotesWrap").hidden=!s.notes;$("spotNotes").textContent=s.notes||"";$("googleMapsLink").href=s.googleMapsUrl||`https://www.google.com/maps/search/?api=1&query=${s.coordinates[1]},${s.coordinates[0]}`;renderPhotos(s.photos||[]);$("groupSwitcher").hidden=currentGroup.length<2;$("groupPosition").textContent=`${currentGroupIndex+1} / ${currentGroup.length}`}
function renderPhotos(photos){const c=$("photoCarousel");c.innerHTML="";(photos.length?photos:[{src:"assets/placeholder.svg",position:"center"}]).forEach((p,i,a)=>{const d=document.createElement("div");d.className="photo-slide";const img=document.createElement("img");img.src=p.src;img.alt=`${$("spotName").textContent}の写真 ${i+1}`;img.style.objectPosition=p.position||"center";img.draggable=false;d.appendChild(img);if(a.length>1){const dots=document.createElement("div");dots.className="photo-dots";a.forEach((_,j)=>{const dot=document.createElement("span");dot.className=`photo-dot${j===i?" active":""}`;dots.appendChild(dot)});d.appendChild(dots)}c.appendChild(d)});c.scrollLeft=0}
function closeSheet(){$("spotSheet").classList.remove("is-open");$("spotSheet").setAttribute("aria-hidden","true");markers.forEach(m=>m.button.classList.remove("is-selected"))}
function selectedArray(f,key){return key==="categories"?f.categories:(f.tags[key]||=[])}
function initFilters(){const host=$("filterGroups");const add=(label,key,vals)=>{const sec=document.createElement("section");sec.className="filter-section";sec.innerHTML=`<h2>${label}</h2><div class="chip-list"></div>`;vals.forEach(v=>{const b=document.createElement("button");b.type="button";b.className="filter-chip";b.textContent=v;b.dataset.filterKey=key;b.dataset.value=v;b.onclick=()=>{const a=selectedArray(draftFilters,key),i=a.indexOf(v);i>=0?a.splice(i,1):a.push(v);syncFilterUI()};sec.lastChild.appendChild(b)});host.appendChild(sec)};add("カテゴリー","categories",filterSpec.categories);filterSpec.tagGroups.forEach(g=>add(g.label,g.label,g.tags))}
function syncFilterUI(){document.querySelectorAll(".filter-chip").forEach(b=>b.setAttribute("aria-pressed",String(selectedArray(draftFilters,b.dataset.filterKey).includes(b.dataset.value))));const n=filteredSpots(draftFilters).length;$("resultCount").textContent=`該当するスポット：${n}件`;$("zeroMessage").hidden=n!==0;$("applyFilters").disabled=n===0}
const hasFilters=f=>f.categories.length||Object.values(f.tags).some(a=>a.length);
function showToast(msg){clearTimeout(toastTimer);$("toast").textContent=msg;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),3000)}
function insideBounds(lng,lat){const b=cfg.maxBounds;return lng>=b[0][0]&&lng<=b[1][0]&&lat>=b[0][1]&&lat<=b[1][1]}
function locate(){if(lastPosition){map.easeTo({center:[lastPosition.coords.longitude,lastPosition.coords.latitude],zoom:15,duration:500});return}if(!map){showToast("地図を読み込んでいます");return}if(!navigator.geolocation){showToast("この端末では現在地を利用できません");return}navigator.geolocation.getCurrentPosition(pos=>{const lng=pos.coords.longitude,lat=pos.coords.latitude;if(!insideBounds(lng,lat)){showToast("現在地はOKINAMAPの表示範囲外です");return}lastPosition=pos;if(!userMarker){const anchor=document.createElement("div");anchor.className="marker-anchor";const pin=document.createElement("div");pin.className="current-location-pin";pin.ariaLabel="現在地";anchor.appendChild(pin);userMarker=new maplibregl.Marker({element:anchor,anchor:"center",offset:[0,0]}).setLngLat([lng,lat]).addTo(map)}else userMarker.setLngLat([lng,lat]);map.easeTo({center:[lng,lat],zoom:15,duration:600})},err=>showToast(err.code===1?"現在地を取得できませんでした。位置情報設定をご確認ください":"現在地を取得できませんでした"),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
$("sheetClose").onclick=closeSheet;$("groupPrev").onclick=()=>{currentGroupIndex=(currentGroupIndex-1+currentGroup.length)%currentGroup.length;showSpot()};$("groupNext").onclick=()=>{currentGroupIndex=(currentGroupIndex+1)%currentGroup.length;showSpot()};$("filterOpen").onclick=()=>{draftFilters=structuredClone(activeFilters);syncFilterUI();$("filterModal").hidden=false};$("filterClose").onclick=()=>{$("filterModal").hidden=true};$("clearFilters").onclick=()=>{draftFilters={categories:[],tags:{}};syncFilterUI()};$("applyFilters").onclick=()=>{activeFilters=structuredClone(draftFilters);$("filterModal").hidden=true;$("filterBadge").hidden=!hasFilters(activeFilters);closeSheet();if(map)renderMarkers()};$("locateButton").onclick=locate;initFilters();initMap()})();