(() => {
  "use strict";
  const cfg=window.OKINAMAP_CONFIG, spots=window.OKINAMAP_SPOTS||[], filterSpec=window.OKINAMAP_FILTERS;
  const $=id=>document.getElementById(id);
  let map, markers=[], activeFilters={categories:[],tags:{}}, draftFilters=structuredClone(activeFilters);
  let currentGroup=[], currentGroupIndex=0, userMarker=null, lastPosition=null, toastTimer;
  const categoryIcons={
    "飲食店":'<path d="M7 3v7M4 3v4c0 2 6 2 6 0V3M7 10v11M15 3v18M15 3c5 2 5 9 0 10"/>',
    "カフェ":'<path d="M5 8h11v7a5 5 0 0 1-5 5h-1a5 5 0 0 1-5-5zM16 10h2a3 3 0 0 1 0 6h-2M8 3c-2 2 2 2 0 4M13 3c-2 2 2 2 0 4"/>',
    "ビーチ":'<path d="M3 15c3-4 6 4 9 0s6 4 9 0M3 20c3-4 6 4 9 0s6 4 9 0M6 11c2-5 10-7 14-3-3 0-4 1-5 3-2-2-4-2-5 0-1-2-2-3-4-3"/>',
    "その他":'<path d="m12 3 2.4 5 5.6.8-4 4 .9 5.7-4.9-2.7-4.9 2.7.9-5.7-4-4 5.6-.8z"/>'
  };
  const validKey=()=>cfg.mapTilerKey&&cfg.mapTilerKey!=="YOUR_MAPTILER_API_KEY";
  const groupedSpots=(list=spots)=>{const groups=new Map();list.forEach(spot=>{const key=spot.groupId||`single:${spot.id}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(spot)});return [...groups.values()]};
  const markerSvg=category=>`<svg viewBox="0 0 24 24" aria-hidden="true">${categoryIcons[category]||categoryIcons["その他"]}</svg>`;
  function initMap(){if(!validKey()){$("setupMessage").hidden=false;return}map=new maplibregl.Map({container:"map",style:cfg.mapStyle.replace("{KEY}",encodeURIComponent(cfg.mapTilerKey)),center:cfg.initialCenter,zoom:cfg.initialZoom,minZoom:cfg.minZoom,maxZoom:cfg.maxZoom,maxBounds:cfg.maxBounds,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:false}),"bottom-right");map.addControl(new maplibregl.AttributionControl({compact:true}),"bottom-right");map.on("load",renderMarkers)}
  function filteredSpots(filters){return spots.filter(spot=>{const categoryOk=!filters.categories.length||filters.categories.includes(spot.category);const selectedGroups=Object.values(filters.tags).filter(arr=>arr.length);return categoryOk&&selectedGroups.every(tags=>tags.some(tag=>spot.tags.includes(tag)))})}
  function renderMarkers(){markers.forEach(item=>item.marker.remove());markers=[];groupedSpots(filteredSpots(activeFilters)).forEach(group=>{const primary=group[0],holder=document.createElement("div");holder.className="marker-holder";const button=document.createElement("button");button.type="button";button.className="custom-marker";button.innerHTML=markerSvg(primary.category);button.setAttribute("aria-label",group.length>1?`${group.length}件のスポット`:primary.name);button.addEventListener("click",e=>{e.stopPropagation();openGroup(group)});holder.appendChild(button);if(group.length>1){const badge=document.createElement("span");badge.className="count-badge";badge.textContent=String(group.length);holder.appendChild(badge)}const marker=new maplibregl.Marker({element:holder,anchor:"bottom"}).setLngLat(primary.coordinates).addTo(map);markers.push({marker,button,ids:group.map(s=>s.id)})})}
  function openGroup(group){currentGroup=group;currentGroupIndex=0;markers.forEach(m=>m.button.classList.toggle("is-selected",m.ids.some(id=>group.some(s=>s.id===id))));showSpot();$("spotSheet").classList.add("is-open");$("spotSheet").setAttribute("aria-hidden","false");const cardHeight=Math.min($("spotSheet").scrollHeight||360,innerHeight*.52);map.easeTo({center:group[0].coordinates,offset:[0,-cardHeight*.42],duration:420})}
  function showSpot(){const spot=currentGroup[currentGroupIndex];$("spotName").textContent=spot.name;$("spotCategory").textContent=spot.category;$("spotDescription").textContent=spot.description;$("spotNotesWrap").hidden=!spot.notes;$("spotNotes").textContent=spot.notes||"";$("googleMapsLink").href=spot.googleMapsUrl||`https://www.google.com/maps/search/?api=1&query=${spot.coordinates[1]},${spot.coordinates[0]}`;renderPhotos(spot.photos||[]);const multiple=currentGroup.length>1;$("groupSwitcher").hidden=!multiple;$("groupPosition").textContent=`${currentGroupIndex+1} / ${currentGroup.length}`}
  function renderPhotos(photos){const carousel=$("photoCarousel");carousel.innerHTML="";const list=photos.length?photos:[{src:"assets/placeholder.svg",position:"center"}];list.forEach((photo,index)=>{const slide=document.createElement("div");slide.className="photo-slide";const img=document.createElement("img");img.src=photo.src;img.alt=`${$("spotName").textContent}の写真 ${index+1}`;img.style.objectPosition=photo.position||"center";img.draggable=false;slide.appendChild(img);if(list.length>1){const dots=document.createElement("div");dots.className="photo-dots";list.forEach((_,i)=>{const dot=document.createElement("span");dot.className=`photo-dot${i===index?" active":""}`;dots.appendChild(dot)});slide.appendChild(dots)}carousel.appendChild(slide)});carousel.scrollLeft=0}
  function closeSheet(){$("spotSheet").classList.remove("is-open");$("spotSheet").setAttribute("aria-hidden","true");markers.forEach(m=>m.button.classList.remove("is-selected"))}
  function initFilters(){const wrap=$("filterGroups");wrap.innerHTML="";createFilterSection("カテゴリー","categories",filterSpec.categories);filterSpec.tagGroups.forEach(group=>createFilterSection(group.label,group.label,group.tags))}
  function createFilterSection(label,key,values){const section=document.createElement("section");section.className="filter-section";section.innerHTML=`<h2>${label}</h2><div class="chip-list"></div>`;const list=section.querySelector(".chip-list");values.forEach(value=>{const button=document.createElement("button");button.type="button";button.className="filter-chip";button.textContent=value;button.dataset.filterKey=key;button.dataset.value=value;button.setAttribute("aria-pressed","false");button.addEventListener("click",()=>toggleDraft(key,value));list.appendChild(button)});$("filterGroups").appendChild(section)}
  const selectedArray=(filters,key)=>key==="categories"?filters.categories:(filters.tags[key]||=[]);
  function toggleDraft(key,value){const arr=selectedArray(draftFilters,key),index=arr.indexOf(value);index>=0?arr.splice(index,1):arr.push(value);syncFilterUI()}
  function syncFilterUI(){document.querySelectorAll(".filter-chip").forEach(button=>button.setAttribute("aria-pressed",String(selectedArray(draftFilters,button.dataset.filterKey).includes(button.dataset.value))));const count=filteredSpots(draftFilters).length;$("resultCount").textContent=`該当するスポット：${count}件`;$("zeroMessage").hidden=count!==0;$("applyFilters").disabled=count===0}
  const hasFilters=filters=>filters.categories.length>0||Object.values(filters.tags).some(arr=>arr.length>0);
  function openFilters(){draftFilters=structuredClone(activeFilters);syncFilterUI();$("filterModal").hidden=false}
  function showToast(message){clearTimeout(toastTimer);$("toast").textContent=message;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),3000)}
  function insideBounds(lng,lat){const b=cfg.maxBounds;return lng>=b[0][0]&&lng<=b[1][0]&&lat>=b[0][1]&&lat<=b[1][1]}
  function locate(){if(lastPosition){map.easeTo({center:[lastPosition.coords.longitude,lastPosition.coords.latitude],zoom:15,duration:500});return}if(!map){showToast("地図を読み込んでいます");return}if(!navigator.geolocation){showToast("この端末では現在地を利用できません");return}navigator.geolocation.getCurrentPosition(position=>{const lng=position.coords.longitude,lat=position.coords.latitude;if(!insideBounds(lng,lat)){showToast("現在地はOKINAMAPの表示範囲外です");return}lastPosition=position;if(!userMarker){const el=document.createElement("div");el.className="current-location-pin";el.setAttribute("aria-label","現在地");userMarker=new maplibregl.Marker({element:el,anchor:"bottom"}).setLngLat([lng,lat]).addTo(map)}else userMarker.setLngLat([lng,lat]);map.easeTo({center:[lng,lat],zoom:15,duration:600})},error=>showToast(error.code===1?"現在地を取得できませんでした。位置情報設定をご確認ください":"現在地を取得できませんでした"),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
  $("sheetClose").addEventListener("click",closeSheet);$("groupPrev").addEventListener("click",()=>{currentGroupIndex=(currentGroupIndex-1+currentGroup.length)%currentGroup.length;showSpot()});$("groupNext").addEventListener("click",()=>{currentGroupIndex=(currentGroupIndex+1)%currentGroup.length;showSpot()});$("filterOpen").addEventListener("click",openFilters);$("filterClose").addEventListener("click",()=>{$("filterModal").hidden=true});$("clearFilters").addEventListener("click",()=>{draftFilters={categories:[],tags:{}};syncFilterUI()});$("applyFilters").addEventListener("click",()=>{activeFilters=structuredClone(draftFilters);$("filterModal").hidden=true;$("filterBadge").hidden=!hasFilters(activeFilters);closeSheet();if(map)renderMarkers()});$("locateButton").addEventListener("click",locate);
  initFilters();initMap();
})();
